### ISSUE TITLE
error on linux

### ISSUE THREAD

**Issue by staf4d** [ddark/ecl#1]
/root/Blackwingevo/blackwingevo/src/server/game/Anticheat/AnticheatMgr.cpp: In member function 'void AnticheatMgr::BuildReport(Player_, uint8)':
/root/Blackwingevo/blackwingevo/src/server/game/Anticheat/AnticheatMgr.cpp:339:74: error: cannot pass objects of non-trivially-copyable type 'const string {aka const class std::basic_string<char>}' through '...'
make[2]: *_\* [src/server/game/CMakeFiles/game.dir/Anticheat/AnticheatMgr.cpp.o] Error 1
make[1]: **\* [src/server/game/CMakeFiles/game.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ddark** [comment]
https://github.com/ddark/ecl/commit/433f39c01ae63c198f3e0332bde0534d1204adec исправил
