### ISSUE TITLE
Выложите пожалуйста свою базу (world.sql)

### ISSUE THREAD

**Issue by Willem86** [ddark/ecl#11]
Возможно я что то не так сделал, но у меня в TDB нету лута в инстах работоспособность на высоком уровне , YTDB работает на так себе хотя терпимо если только для пвп,, и вы молодец умеете делать хорошие сборки

**Comment by ddark** [comment]
Вот держи http://turbobit.net/95qxv7pw53k7.html

**Comment by Willem86** [comment]
Огромное спасибо

**Comment by ddark** [comment]
незашто
