### ISSUE TITLE
Баг со всеми мобами.

### ISSUE THREAD

**Issue by staf4d** [ddark/ecl#6]
Проблема в следующем (думал что дело в синдре и лане) иногда (один из 100, но это может быть босс) мобы багаются, любыми магиями и ударами по ним попасть нельзя и они стоят на месте в не зависимости от того есть ли комбат. помогает только .un in all или .die (.damage тоже не проходит)

**Comment by staf4d** [comment]
и еще оффтоп. планируете ли вы дальше поддерживать свое ядро или это финальная версия и больше вы ничего делать не будете? Хотел сказать вам огромное спасибо за это ядро, других подобных не встречал нигде. Единственное достойное ядро. Еще раз спасибо.

**Comment by ddark** [comment]
Буду поддерживать и это не финальная версия

**Comment by staf4d** [comment]
ясно.
