### ISSUE TITLE
ИЧ, ИК

### ISSUE THREAD

**Issue by staf4d** [ddark/ecl#7]
ИЧ нету стартового ивента (пустой диалог у нипа)
ИК багается моб, который начинает ивенты, на разных фазах. (иногда лечится .die, .respawn или .gm on), иногда не лечится.

**Comment by ddark** [comment]
ич http://imageshack.com/a/img836/1513/8lvw.jpg и http://imageshack.com/a/img14/5509/8heo.jpg впорядке

**Comment by staf4d** [comment]
ytdb 640 + вроде все патчи из sql/updates
за альянс просто "Greetings, Nickname", за орду все как у вас на скринах, НО при нажатии "Я готов" ничего не происходит. Можете залить базу свою куда-нибудь? И еще, как сделать нормальные цены, а то все можно продать только по 11 медяков.

**Comment by ddark** [comment]
моя база под фан

**Comment by staf4d** [comment]
а на счет других вопросов?

**Comment by ddark** [comment]
ик вроди пронёс но после смерти как у вас

**Comment by staf4d** [comment]
Могу я все-равно получить вашу базу? А на счет цен и еще, как fake online сделать, а то инфы нету нигде?

**Comment by ddark** [comment]
щас дам базу fake online у меня тоже мало инфы я непроверял его толком

**Comment by staf4d** [comment]
еще раз огромное спасибо за ваш труд. все копирайты обязуюсь сохранить. на свое творение вы сможете посмотреть тут: blackwing-wow.ru (хотя мала вероятность, что вам оно надо)
